FROM golang:1.22 AS builder

WORKDIR /app/counter

COPY ./src/counter /app/counter

RUN go get . && \
    go test . && \
    go build -o counter && \
    chmod a+x counter

FROM alpine:latest AS final

EXPOSE 8080

WORKDIR /app

COPY --from=builder /app/counter/counter /app/counter

ENTRYPOINT [ "/app/counter" ]
