name: GO Toybox Counter

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  counter:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
      credentials:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd src/counter
          go build -o counter
          ./counter 1 20
