name: GO Toybox Counter

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  counter:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - name: Test counter
        run: |
          go get .
          go test -v ./...
        working-directory: ./src/counter
      - name: Build counter
        run: |
          go build -o counter
          chmod a+x counter
        working-directory: ./src/counter
      - name: Run counter
        run: ./counter 0 9
        working-directory: ./src/counter
