name: GO Toybox Counter

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  counter:
    runs-on: ubuntu-latest
    container:
      image: golang:1.22
      credentials:
        username: ${{ github.DOCKER_USENAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      # - name: Set up Go
      #   uses: actions/setup-go@v4
      #   with:
      #     go-version: 1.22
      #     cache: true
      #     b
      - run: ls -al
      # - uses: ./.github/templates/test-paths
      #   with:
      #     who-to-greet: 'Plan'