name: GO Toybox Math

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  SRC_PATH: ${{ github.workspace }}/src/math

jobs:
  math:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Test math
        run: |
          go get .
          go test -v ./...
        working-directory: ${{ env.SRC_PATH }}
      - name: Build math
        run: |
          go build -o math
          chmod a+x math
        working-directory: ${{ env.SRC_PATH }}
