name: GO Toybox WhichOS

on:
  workflow_dispatch:
  push:
    branches:
      - whichos

env:
  SRC_PATH: ${{ github.workspace }}/src/whichos

jobs:
  whichos:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22
      - uses: actions/checkout@v3
      - name: Build and run whichos
        run: |
          go get .
          go build -o whichos
          chmod a+x whichos
          ./whichos
        working-directory: ${{ env.SRC_PATH }}
        
